[book]
authors = ["Steven Hé (Sīchàng)"]
language = "en"
multilingual = false
src = "src"
title = "Steven's mdbook katex template"

[build]
build-dir = "_site"

[output.html]
git-repository-url = "https://github.com/SichangHe/mdbook_katex_template"

[preprocessor.katex]
after = ["links"]
include-src = true

[preprocessor.toc]
before = ["katex"]
