name: Build and deploy mdBook site
on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: Build with mdBook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install mdBook and mdBook-KaTeX
      run: |
        cargo install mdbook --version 0.5.4
        cargo install --git https://github.com/SichangHe/mdbook-katex.git --rev f623f031d705ec96e5f747b8c3a910ef1a32734b --locked
    - name: Build
      run: mdbook build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: _site

  deploy:
    name: Deploy the site to GitHub Pages
    needs: build
    if: github.event_name == 'push'
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
