name: Build
on: [push, pull_request]

jobs:
  build:
    name: Build with mdBook
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cargo-bins/cargo-binstall@main
    - name: Install mdBook and mdBook-KaTeX
      run: cargo binstall -y mdbook mdbook-katex
    - name: Build
      run: mdbook build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          preview: ${{ github.event_name != 'push' }}
